services:
  app:
    build: .
    container_name: laravel_app
    depends_on:
      - db
    volumes:
      - .:/var/www
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:randomkeyhere

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Eksternal 3307 -> Internal 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
